---
development:
  cloud_name: hhowosfol
  api_key: '711373451895137'
  api_secret: rNmdol1nOuRsoFgPvju-NhMxnOE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hhowosfol
  api_key: '711373451895137'
  api_secret: rNmdol1nOuRsoFgPvju-NhMxnOE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hhowosfol
  api_key: '711373451895137'
  api_secret: rNmdol1nOuRsoFgPvju-NhMxnOE
  enhance_image_tag: true
  static_image_support: false
